# Generated by Django 5.1.1 on 2024-10-11 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
