# Generated by Django 5.1.1 on 2024-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='show',
            field=models.BooleanField(default=1),
        ),
    ]
