# Generated by Django 5.1.1 on 2024-10-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_category_articles_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aextra',
            fields=[
                ('sticky', models.BooleanField(default=False, verbose_name='سنجاق')),
                ('tags', models.CharField(max_length=100, verbose_name='تگ')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.articles')),
            ],
        ),
    ]
